Repository MobileAppsProjects/kotlin-dev, pull requests merged in 2024-05, with the labels that each got.

#47 LogOutActivity
  .idea/.gitignore
  .idea/appInsightsSettings.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/kotlin-dev.iml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  RestaurantApp/app/src/main/java/com/example/restaurantapp/ui/LogOutActivity.kt
Labels: good first issue

#53 Home view created
  .idea/workspace.xml
  RestaurantApp/app/src/main/java/com/example/restaurantapp/HomeActivity.java
  RestaurantApp/app/src/main/res/layout/activity_home.xml
Labels: help wanted

#56 create the class HomeActivity
  .idea/workspace.xml
  RestaurantApp/app/src/main/java/com/example/restaurantapp/HomeActivity.java
  RestaurantApp/app/src/main/java/com/example/restaurantapp/HomeActivity.kt
Labels: help wanted

#58 Map created
  .idea/workspace.xml
  RestaurantApp/app/build.gradle.kts
  RestaurantApp/app/src/main/java/com/example/restaurantapp/MapFragment.kt
  RestaurantApp/app/src/main/res/layout/map_fragment.xml
Labels: bug

#57 Eventual Connectivity debugged
  RestaurantApp/app/src/main/java/com/example/restaurantapp/MainActivity.kt
  RestaurantApp/app/src/main/java/com/example/restaurantapp/NetworkService.kt
Labels: enhancement

#62 Main Activity Imporvement
  RestaurantApp/app/src/main/java/com/example/restaurantapp/MainActivity.kt
Labels: enhancement

#64 cache implemented
  .idea/workspace.xml
  RestaurantApp/app/src/main/java/com/example/restaurantapp/MainActivity.kt
  RestaurantApp/app/src/main/java/com/example/restaurantapp/RestaurantMenuActivity.kt
  RestaurantApp/app/src/main/java/com/example/restaurantapp/adapter/RestaurantListAdapter.kt
Labels: optimization

#67 Main Activity Final Update
  RestaurantApp/app/src/main/java/com/example/restaurantapp/MainActivity.kt
Labels: enhancement

#73 Restaurant dataclass
  .idea/deploymentTargetSelector.xml
  .idea/workspace.xml
  RestaurantApp/app/src/main/java/com/example/restaurantapp/Localstorage/Restaurant.kt
Labels: enhancement

#74 Dataclass Menu
  .idea/workspace.xml
  RestaurantApp/app/src/main/java/com/example/restaurantapp/Localstorage/Menu.kt
Labels: enhancement

#86 Develop
  .idea/appInsightsSettings.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/workspace.xml
  RestaurantApp/app/src/main/java/com/example/restaurantapp/HomeActivity.kt
  RestaurantApp/app/src/main/java/com/example/restaurantapp/ui/LogOutActivity.kt
  RestaurantApp/app/src/main/res/layout/activity_home.xml
Labels: enhancement

#88 Changes Final
  .idea/workspace.xml
Labels: optimization
